version: "3"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-demo
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq_network

  producer:
    build: ./producer
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"
    networks:
      - rabbitmq_network

  consumer:
    build: ./consumer
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge
